
version: "3.8"
services:
#  postgres:
#    container_name: postgres_Employee
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#      POSTGRES_DB: Employee_db
#    ports:
#      - "5432:5432"
  postgres:
    container_name: postgres_Employee
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: Employee_db
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_Employee
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "6060:80"
